- sound-theme-player/utils.go
https://github.com/linuxdeepin/internal-discussion/issues/1201
> feat(sound-theme-player): add retry for alsactl restore

- device/device.go
- locale-helper/ifc.go
https://bugzilla.suse.com/show_bug.cgi?id=1070943
> fix(device): checkAuthorization is not secure

- debian/control
use fonts-unifont replace ttf-unifont
Log:
Resolve https://github.com/linuxdeepin/developer-center/issues/3188
> refactor: replace ttf-unifont

- archlinux/PKGBUILD
- archlinux/deepin-api.install
- archlinux/deepin-api.sysusers
> add archlinux build

- Makefile
- misc/scripts/deepin-boot-sound.sh
- misc/systemd/system/deepin-login-sound.service
在脚本后台执行播放启动音效
Log:
Bug: https://pms.uniontech.com/bug-view-152901.html
Influence: 开机音效
Change-Id: Ib926f2cb19eeb4fe4c2440af53f65ab05123e1f9
> fix: 在脚本后台执行播放开机音效

- debian/changelog
- misc/scripts/deepin-boot-sound.sh
fix lintain
Log: fix lintain
Influence: 无
Change-Id: I4305c36758e18b95bd7689a3de266613c4f9f812
> chore: fix lintain

- README.md
- README.zh_CN.md
The protocol name in the README is written according to the standard specification
Log: modify README license information
Influence: none
Task: https://pms.uniontech.com/task-view-185215.html
Change-Id: I75273abee88dd82bc6217a0ed8f3b8b39028db63
> chore: modify README license information

- dde-open/main.go
使用golang自带的url解析库存在部分问题，改用gio的解析方式获取对应scheme
Log: 修复dde-open解析部分url无法获取到scheme问题
Bug: https://pms.uniontech.com/bug-view-162007.html
Influence: dde-open打开url
Change-Id: Iba0724f9bb4c714ba5f3331d4558019bdc934b5f
> fix: 修复dde-open解析部分url无法获取到scheme问题

- .reuse/dep5
- .tx/config
- .tx/deepin.conf
- debian/changelog
Changelog
* release dde-api 6.0.5
Log:
> chore: bump version to 6.0.5

- debian/changelog
> chore: tag 6.5.6

- .gitignore
- gen.go
> chore: add gen.go support

- Makefile
- debian/rules
move GO111MODULE=off to debain rules
Log:
> chore: Makefile can use go mod

- deepin-shutdown-sound/main.go
先屏蔽关机音效，待修复关机噪音
Log: 解决关机音效存在杂音的问题
> fix: 关机音效存在杂音

- powersupply/battery/battery.go
> chore: correct a typo in battery.go

- thumbnails/font/thumbnail.c
gsize是 unsigned int ，不应该返回-1
Log: 函数返回值不合法
Influence: 无
Change-Id: Ie32089641a60a80f99ee83cd422e8ce2c79629f4
> chore: 函数返回值不合法

- adjust-grub-theme/main.go
try to get primary screen resolution from xrandr
Ref: https://github.com/martyr-deepin/deepin-installer-reborn/blob/b3fa4a16f0634a1c162e5358922c7abfc2798254/hooks/before_chroot/31_get_screen_resolution.job#L6-L22
Ref: https://github.com/linuxdeepin/developer-center/issues/5436
> feat(adjust-grub-theme): getScreenSizeFromXrandr

- misc/systemd/system/deepin-login-sound.service
- misc/systemd/system/deepin-shutdown-sound.service
See https://en.opensuse.org/openSUSE:Security_Features#Systemd_hardening_effort
> Added hardening to systemd services

- adjust-grub-theme/main.go
Beta 2 放弃：
1. dde-api 根据 xrandr 生成主题
2. deepin-installer GFXMODE=auto
This reverts commit 006a25ded65d8aaf0a3c7250907b8b2c36d0a288.
> fix: Revert "feat: adjust-grub-theme: get screen size from xrandr"

- debian/control
> chore: switch dep from libfreetype6 to libfreetype

- dde-open/main.go
fix: dde-open error when use old am
> fix: dde-open error when use old am

- debian/changelog
- deepin-shutdown-sound/main.go
- misc/systemd/system/deepin-shutdown-sound.service
> fix: no shutdown sound 

- adjust-grub-theme/adjust_grub_theme_test.go
- adjust-grub-theme/main.go
- adjust-grub-theme/testdata/os-version
> fix: 解决单元测试不通过的问题

- sound-theme-player/main.go
避免首次开机时报错
Bug: https://pms.uniontech.com/bug-view-282785.html
> chore: ignore the error of getLastUser
